name: default

channels:
  - conda-forge
  - defaults

dependencies:
  - python >=3.6,<3.7
  - importnb >=0.5.2
  - ipykernel >=5.1
  - ipython >=7.2
  - jupyterlab >=0.35.4,<0.36
  - nodejs >=8.12,<9
  - pillow
  - robotframework >=3.1
